//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: AssemblyCompany("USDA FS")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: AssemblyFileVersion("0.1.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0")]
[assembly: AssemblyProduct("National Cruise System")]
[assembly: AssemblyTitle("National Cruise System")]
[assembly: AssemblyVersion("0.1.0.0")]

// Generated by the MSBuild WriteCodeFragment class.

